#!groovy
properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '7', numToKeepStr: '3')), [$class: 'ScannerJobProperty', doNotScan: false]])
node {
	deleteDir() // Purge workspace
	// Checkout the repo to get the necessary groovy scripts (and place it in the required subdirectory)
	dir('hardware/MySensors/nRF5') {
		checkout scm
	}
	def pipeline = load('hardware/MySensors/nRF5/.ci/pipeline.groovy')

	// Invoke the main pipeline
	pipeline {
		library_root = 'MySensors/'                  // Location of the MySensors library
		repository_root = 'hardware/MySensors/nRF5/' // Location of the repository root
		github_organization = 'mysensors'            // Name of the GitHub Organization
		repository_name = 'ArduinoHwNRF5'            // Name of the repository on GitHub
		nightly_arduino_ide = false                  // Pick Arduino IDE variant to use
	}
}
